### ISSUE TITLE
Version 0.8.1 cannot find config.json

### ISSUE THREAD

**Issue by Tom2527** [jordanryanmoore/homebridge-scout#65]
### Description
Version 0.8.1 cannot find config.json

### Reproduction Steps
After upgrading from 0.7.1 to 0.8.1 I get the following error. 
Not sure if it's a bug, or a config issue on my end. Downgrading to 0.7.1 fixes the issue.

[2/15/2020, 11:34:04 PM] Error: Cannot find module '../../schema/config.json'
Require stack:
- /usr/local/lib/node_modules/homebridge-scout/lib/context/homebridge.js
- /usr/local/lib/node_modules/homebridge-scout/lib/context/index.js
- /usr/local/lib/node_modules/homebridge-scout/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at new HomebridgeContextFactory (/usr/local/lib/node_modules/homebridge-scout/lib/context/homebridge.js:12:23)
    at new <anonymous> (/usr/local/lib/node_modules/homebridge-scout/lib/index.js:20:28)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by jordanryanmoore** [comment]
I've pushed a fix to master, but I'm going to release the fix to the 0.8.x branch instead of waiting for the next minor release.

**Comment by jordanryanmoore** [comment]
This should be fixed in master and 0.8.2 now.

**Comment by Tom2527** [comment]
unfortunately, the issue has not been fixed in version 0.8.2

**Comment by jordanryanmoore** [comment]
Well, crap. I rushed the last (attempted) fix, and now it might be a week or more before I can get a real fix out.

**Comment by jordanryanmoore** [comment]
*Should* be fixed in 0.8.3 now… 🤞
